name: emo
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - jupyter
  - matplotlib
  - seaborn
  - evaluate
  - datasets 
  - huggingface_hub 
  - ipywidgets
  - 'transformers[torch]'
  - transformers-4.28.1
  - pytorch
  - plotnine
  - tqdm
